services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/release-notes-data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_PASSWORD}
    ports:
      - "8081:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    volumes:
      - keycloak_data:/opt/keycloak/release-notes-data

volumes:
  db_data:
  keycloak_data: