spring.application.name=Release Notes Portal (CI)

management.endpoint.health.access=read-only

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.docker.compose.enabled=false
# Hard-coded since environment variables are not needed in temporary in-memory database
spring.datasource.username=ci_username
spring.datasource.password=ci_password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-ci.sql

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=${OPENAI_URL}
spring.ai.openai.chat.options.model=${OPENAI_MODEL}